/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'publishedAt' : bigint,
  'author' : string,
  'imageUrl' : string,
  'excerpt' : string,
  'category' : string,
}
export interface Lead {
  'name' : string,
  'email' : string,
  'loanType' : string,
  'timestamp' : bigint,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPost' : ActorMethod<
    [string, string, string, string, string, string, bigint],
    BlogPost
  >,
  'deletePost' : ActorMethod<[bigint], undefined>,
  'getAllLeads' : ActorMethod<[], Array<Lead>>,
  'getAllPosts' : ActorMethod<[], Array<BlogPost>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPost' : ActorMethod<[bigint], [] | [BlogPost]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'submitLead' : ActorMethod<[string, string, string, string, bigint], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];